#!/bin/bash

echo "開始離線安裝套件..."

PKM_DIR=$(pwd)/pkm
INSTALL_DIR="/opt"

mkdir -p "$INSTALL_DIR"

# ========== 解壓與安裝 ==========
echo "處理各安裝包到 $INSTALL_DIR ..."

#Cocoapods
echo "安裝 CocoaPods 相關 gem 套件..."
cd "$PKM_DIR/cocoapods"
gem install --local zeitwerk-2.7.1.gem
gem install --local activesupport-6.1.7.10.gem
gem install --local nap-1.1.0.gem
gem install --local rexml-3.4.1.gem
gem install --local cocoapods-downloader-1.6.3.gem
gem install --local cocoapods-core-1.12.1.gem
gem install --local xcodeproj-1.27.0.gem
gem install --local nanaimo-0.4.0.gem
gem install --local concurrent-ruby-1.0.5.gem
gem install --local public_suffix-4.0.7.gem
gem install --local colored2-3.1.2.gem
gem install --local addressable-2.8.7.gem
gem install --local cocoapods-1.12.1.gem

# Maven
echo "複製 maven 到 $INSTALL_DIR/maven"
cp -r "$PKM_DIR/maven" "$INSTALL_DIR/maven"

# Go
echo "複製 go 到 $INSTALL_DIR/go"
cp -r "$PKM_DIR/go" "$INSTALL_DIR/go"

# Gradle
echo "複製 gradle 到 $INSTALL_DIR/gradle"
cp -r "$PKM_DIR/gradle" "$INSTALL_DIR/gradle"

# Node.js
echo "複製 node 到 $INSTALL_DIR/node"
cp -r "$PKM_DIR/node" "$INSTALL_DIR/node"

#Python
echo "安裝 Python..."
sudo installer -pkg "$PKM_DIR/python-3.13.3.pkg" -target /

# pip
mkdir -p "$INSTALL_DIR/pip"
cp "$PKM_DIR/pip.pyz" "$INSTALL_DIR/pip/pip"
chmod +x "$INSTALL_DIR/pip/pip"
ln -sf "$INSTALL_DIR/pip/pip" /usr/local/bin/pip

# Ruby
echo "安裝 Ruby 到 $INSTALL_DIR/ruby"
cp -r "$PKM_DIR/ruby" "$INSTALL_DIR/ruby"

# Dotnet(Nuget)
echo "安裝 Dotnet(Nuget)..."
sudo installer -pkg "$PKM_DIR/dotnet-sdk-8.0.408-osx-arm64.pkg" -target /


# ========== 設定環境變數 ==========
echo "設定 ~/.zprofile 環境變數..."

cat <<EOL >> ~/.zprofile
export MAVEN_HOME=$INSTALL_DIR/maven
export GOROOT=$INSTALL_DIR/go
export GRADLE_HOME=$INSTALL_DIR/gradle
export NODE_HOME=$INSTALL_DIR/node
export RUBY_HOME=$INSTALL_DIR/ruby
export PHP_HOME=$INSTALL_DIR/php
export PIP_HOME=$INSTALL_DIR/pip

export PATH=\$MAVEN_HOME/bin:\$GOROOT/bin:\$GRADLE_HOME/bin:\$NODE_HOME/bin:\$RUBY_HOME/bin:\$PHP_HOME/bin:\$PIP_HOME:\$PATH
export PATH="\$(gem environment gemdir)/bin:\$PATH"
EOL

source ~/.zprofile

echo "========== Maven =========="
mvn -v
echo "========== Go =========="
go version
echo "========== Gradle =========="
gradle -v
echo "========== Node.js =========="
node -v
echo "========== Python =========="
python --version
echo "========== Pip =========="
pip3 --version
echo "========== Ruby =========="
ruby -v
echo "========== Nuget =========="
nuget -v
echo "========== CocoaPods =========="
pod --version
